name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test py
    runs-on: ubuntu-latest
    strategy: 
      fail-fast: false
    steps:
    - name: Set
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - uses: actions/checkout@v2
    - name: Test All
      working-directory: ./go
      run: go test ./...
